import { ImageItem } from "@/types/gallery";

export const IMAGES: ImageItem[] = [
  {
    id: "1",
    src: "/gallery/11-800x600.jpg",
    alt: "Misty mountain ridge in the morning",
    title: "Morning Mist Ridge",
    description: "A serene morning with clouds hugging the mountain ridge.",
    tags: ["mountain", "mist", "morning"],
    width: 1080,
    height: 720,
  },
  {
    id: "2",
    src: "/gallery/193-800x600.jpg",
    alt: "Waterfall cascading in a dense forest",
    title: "Hidden Forest Falls",
    description: "A secluded waterfall flowing through lush green trees.",
    tags: ["waterfall", "forest", "nature"],
    width: 1080,
    height: 1350,
  },
  {
    id: "3",
    src: "/gallery/233-800x600.jpg",
    alt: "Pine valley with foggy peaks",
    title: "Foggy Pine Valley",
    description: "Evergreen pine valley shrouded in soft morning fog.",
    tags: ["valley", "pine", "fog"],
    width: 1080,
    height: 720,
  },
  {
    id: "4",
    src: "/gallery/260-800x600.jpg",
    alt: "Glacier lake reflecting snowy cliffs",
    title: "Glacial Reflections",
    description: "Crystal clear lake mirroring the icy cliffs around it.",
    tags: ["lake", "glacier", "reflection"],
    width: 1080,
    height: 1620,
  },
  {
    id: "5",
    src: "/gallery/268-800x600.jpg",
    alt: "Hiker walking along a windy ridge",
    title: "Ridge Hike Adventure",
    description: "A lone hiker braving the winds on a scenic ridge.",
    tags: ["hike", "ridge", "adventure"],
    width: 1080,
    height: 720,
  },
  {
    id: "6",
    src: "/gallery/306-800x600.jpg",
    alt: "Sunlight streaming through forest canopy",
    title: "Sunlit Woodland",
    description: "Golden rays filtering through dense forest trees.",
    tags: ["forest", "sunlight", "trees"],
    width: 1080,
    height: 720,
  },
  {
    id: "7",
    src: "/gallery/315-800x600.jpg",
    alt: "Frozen glacier lake under cloudy sky",
    title: "Icy Lake Panorama",
    description: "An expansive glacier lake beneath overcast skies.",
    tags: ["glacier", "lake", "ice"],
    width: 1080,
    height: 1620,
  },
  {
    id: "8",
    src: "/gallery/344-800x600.jpg",
    alt: "Valley with pine trees and morning mist",
    title: "Emerald Pine Valley",
    description: "A peaceful valley blanketed by soft morning mist.",
    tags: ["valley", "pine", "mist"],
    width: 1080,
    height: 720,
  },
  {
    id: "9",
    src: "/gallery/351-800x600.jpg",
    alt: "Sunrise behind a jagged mountain ridge",
    title: "Sunrise Over Peaks",
    description: "First light illuminating the sharp peaks of the ridge.",
    tags: ["mountain", "sunrise", "ridge"],
    width: 1080,
    height: 720,
  },
  {
    id: "10",
    src: "/gallery/371-800x600.jpg",
    alt: "Forest waterfall in late afternoon light",
    title: "Twilight Forest Falls",
    description: "Golden hour light caressing the flowing waterfall.",
    tags: ["waterfall", "forest", "goldenhour"],
    width: 1080,
    height: 1350,
  },
  {
    id: "11",
    src: "/gallery/585-800x600.jpg",
    alt: "Frozen lake with dramatic cliffs",
    title: "Frozen Reflection",
    description: "Still ice reflecting the surrounding cliffs and sky.",
    tags: ["lake", "frozen", "cliffs"],
    width: 1080,
    height: 1620,
  },
  {
    id: "12",
    src: "/gallery/675-800x600.jpg",
    alt: "Misty valley with pine forests",
    title: "Misty Evergreen Valley",
    description: "Soft morning mist rolling through pine-covered valley.",
    tags: ["valley", "pine", "mist"],
    width: 1080,
    height: 720,
  },
  {
    id: "13",
    src: "/gallery/740-800x600.jpg",
    alt: "Mountain ridge bathed in sunset light",
    title: "Golden Ridge",
    description: "Sunset light painting the rugged ridge in gold tones.",
    tags: ["mountain", "sunset", "ridge"],
    width: 1080,
    height: 720,
  },
  {
    id: "14",
    src: "/gallery/787-800x600.jpg",
    alt: "Forest waterfall cascading into pool",
    title: "Forest Cascade",
    description: "A small waterfall plunging into a crystal-clear pool.",
    tags: ["waterfall", "forest", "cascade"],
    width: 1080,
    height: 1350,
  },
];
